version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: yazanmonshed/hawas:1.0.4
        container_name: hawas
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: hawas
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    webserver:
        image: nginx:alpine 
        container_name: webserverhawas
        restart: unless-stopped
        tty: true
        ports:
            - "81:81"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./nginx.conf.d:/etc/nginx/conf.d/
        networks:
            - app-network
    db:
        image: mysql:5.7.22
        container_name: db_hawas
        restart: unless-stopped
        volumes:    
            - dbdata:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: hawas
            MYSQL_ROOT_PASSWORD: hawas
            SERVICE_TAG: dev
            SERVICE_NAME: mysql
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
volumes:
    dbdata:
        driver: local
